### ISSUE TITLE
Cannot fins shady in role/permission setting

### ISSUE THREAD

**Issue by uart-aplex** [omegacodepl/redmine_shady#1]
I installed it on the Redmine 4.2.0, but I cannot find shady in role and permission setting to let users can use it.

**Comment by omegacodepl** [comment]
Hi.
I looked this up. On my brand new RM 4.2.0 instance i can see this permission without issue.
It's probably not an issue with this plugin.
![image](https://user-images.githubusercontent.com/79839699/116007393-e7e1fe80-a60f-11eb-9a97-2b97da8e3673.png)
![image](https://user-images.githubusercontent.com/79839699/116007423-02b47300-a610-11eb-8d0f-c85d58b1aee6.png)

**Comment by oldenboom** [comment]
Had the same issue on 4.1.1. But upon restarting Redmine the permission did appear.
